### ISSUE TITLE
Test suite build failure w/ ghc 8.8

### ISSUE THREAD

**Issue by DanBurton** [LeapYear/th-test-utils#14]
## Describe the bug

```
/Users/dan/scratch/th-test-utils-1.0.0/test/Main.hs:19:7: error:
    • Illegal visible type application ‘@String’
        Perhaps you intended to use TypeApplications
    • In the untyped splice: $(tryQ $ firstConstrForType "Maybe")
   |
19 |     $(tryQ $ firstConstrForType "Maybe") @?= (Right "Nothing" :: Either String String)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to Reproduce

```bash
stack unpack th-test-utils-1.0.0 && cd th-test-utils-1.0.0
echo 'resolver: nightly-2019-09-29' > stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

## Expected behavior

The test suite should build & run successfully.

## Environment

* Stack version: 2.1.3
* Library version: th-test-utils-1.0.0

## Additional context

(none)

**Comment by brandon-leapyear** [comment]
Hi @DanBurton! So sorry for not responding earlier -- I didn't get a notification for this issue. Can you try with the most up-to-date th-test-utils? 1.0.2 should have support up to GHC 8.10

**Comment by DanBurton** [comment]
Can confirm 1.0.2 builds and passes tests with the latest nightly snapshot. Thanks!

I was able to reproduce this success locally like so:

```bash
stack unpack th-test-utils-1.0.2 && cd th-test-utils-1.0.2
echo 'resolver: nightly-2020-06-16' > stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```
